export const data_clients = [
  {
    id: 1,
    name: 'Admir',
    note: '',
    location: 'Obala Kulina Bana 2',
    phoneNumber: '000-111-222',
    role: 'Developer',
    status: 'Aktivan',
  },
  {
    id: 2,
    name: 'Admir_2',
    note: '',
    location: 'Paromlinska 4',
    phoneNumber: '111-222-333',
    role: 'Full Stack Developer',
    status: 'Aktivan',
  },
  {
    id: 3,
    name: 'Admir_3',
    note: '',
    location: 'Nadežda Petrović 1',
    phoneNumber: '222-333-444',
    role: 'Mobile Developer',
    status: 'Završen',
  },
  {
    id: 4,
    name: 'Admir_4',
    note: '',
    location: 'Location_4',
    phoneNumber: '555-666-777',
    role: 'C# Developer',
    status: 'Završen',
  },
  {
    id: 5,
    name: 'Admir_5',
    note: '',
    location: 'Location_5',
    phoneNumber: '666-777-888',
    role: 'React Developer',
    status: 'Treba se javiti',
  },
]
